### ISSUE TITLE
<tuple> suggested for `std::array`

### ISSUE THREAD

**Issue by hebasto** [include-what-you-use/include-what-you-use#1763]
Here is a minimum reproducible example ( `array_tuple.cpp`):
```c++
#include <array>
#include <string>

void f(std::array<std::array<int, 2>, 3> a) {}

void g(std::string s) {}
```

Toolchain details:
```
$ include-what-you-use --version       
include-what-you-use 0.24 (git:6e08906) based on Ubuntu clang version 20.1.7 (++20250528073343+7cf14539b644-1~exp1~20250528193358.125)
$ clang++-20 -v
Ubuntu clang version 20.1.7 (++20250528073343+7cf14539b644-1~exp1~20250528193358.125)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-20/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/13
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/13
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

IWYU output:
```
$  include-what-you-use array_tuple.cpp 

array_tuple.cpp should add these lines:
#include <tuple>   // for array

array_tuple.cpp should remove these lines:

The full include-list for array_tuple.cpp:
#include <array>   // for array
#include <string>  // for basic_string, string
#include <tuple>   // for array
---
```

Conditions required to reproduce:
1. Clang uses a GCC-13 installation.
2. `<string>` is included.
3. A 2-dimensional array is used.

The issue disappears under other conditions, for example after installing `g++-14`.

**Comment by bolshakov-a** [comment]
Slightly reduced:
```cpp
#include <array>
#include <string>

std::array<int,2> a, *p;
```
IWYU reports forward-declaration of `std::array` from `<tuple>` (line 2019) for some reason, likely because names from `std` cannot be forward-declared in user's code, according to the standard.

**Comment by bolshakov-a** [comment]
Reduced (not standard-conformant code):
```cpp
// Class.h
namespace std {
    template<int>
    class Class{};
}

// fwd.h
namespace std {
    template<int>
    class Class;
}

// fwd-direct.h
#include "fwd.h"

// main.cpp
#include "Class.h"
#include "fwd-direct.h"

std::Class<0> c, *p;
```
```
main.cpp should add these lines:
#include "fwd.h"    // for Class

main.cpp should remove these lines:
- #include "fwd-direct.h"  // lines 2-2

The full include-list for main.cpp:
#include "Class.h"  // for Class
#include "fwd.h"    // for Class
```

**Comment by bolshakov-a** [comment]
Another reproducer is with default template arguments:
```cpp
// Class.h
template<int = 0>
class Class{};

// fwd.h
template<int>
class Class;

// fwd-direct.h
#include "fwd.h"

// main.cpp
#include "Class.h"
#include "fwd-direct.h"

Class<> c, *p;
```
```
main.cpp should add these lines:
#include "fwd.h"    // for Class

main.cpp should remove these lines:
- #include "fwd-direct.h"  // lines 2-2

The full include-list for main.cpp:
#include "Class.h"  // for Class
#include "fwd.h"    // for Class
```
It should be noted that `fwd.h` might really be needed if it were the file containing the declaration with the default argument and not the one in `Class.h`.

**Comment by kimgr** [comment]
I'm having a little trouble reproducing in a repeatable manner, since it depends on such a specific libstdc++ version.

@bolshakov-a I don't fully see how the reduced test cases map to the original problem.

* `class.h` <=> `<array>`
* `fwd.h` <=> `<tuple>`
* `fwd-direct.h` <=> `<string>`

?

And how does the default template argument related to the array/tuple/string trio?

**Comment by bolshakov-a** [comment]
Yeah, correct.

The problem arises on recategorizing fwd-decl uses to full uses:
https://github.com/include-what-you-use/include-what-you-use/blob/c53f6950a20edc2923ff70f9fff4e884580f76af/iwyu_output.cc#L997-L1005

However, I'm not still sure that remapping the use records from a somehow chosen declaration to the definition would be the correct fix not causing any regression (keeping in mind `<iosfwd>`). For the default argument case, an even more elaborated handling is needed, I think.

**Comment by kimgr** [comment]
> For the default argument case, an even more elaborated handling is needed, I think.

... because we have to make sure to further filter redecls, and pick one declaration that declares the default arguments?

Ah, I see A2 and A3 deal with these exact cases, now I understand why the default template params were relevant. Thanks!

**Comment by bolshakov-a** [comment]
> ... because we have to make sure to further filter redecls, and pick one declaration that declares the default arguments?

Yeah, default arguments may be even smeared over several declarations, like this:
```cpp
template <class T1, class T2 = int>
class Tpl;

template <class T1 = char, class T2>
class Tpl;

Tpl<> *p;
```
And when all the template arguments are explicitly specified at the use site, a fwd-declaration is Ok.

**Comment by bolshakov-a** [comment]
Btw, fwd-decl uses of symbols from `__gnu_cxx` need not to be recategorized to full uses. They should simply not occur (except the case when a user writes it explicitly). A fwd-decl use of a symbol not typed by the user would mean an IWYU bug. In fact, IWYU does still contain such bugs, and they should be fixed at first...

**Comment by bolshakov-a** [comment]
I've opened #1774 so that that bugs would not be lost if something happens with me.

**Comment by firewave** [comment]
> keeping in mind `<iosfwd>`

That is still not handled properly - the issues are shadowed by internal mappings. See #1683.

**Comment by bolshakov-a** [comment]
I suspect that an additional field should be added into mappings showing that a fwd-decl use of e.g. `basic_istream` should be mapped to `<iosfwd>`, whereas a full use should be mapped to `<istream>`. This field could be fully internal, i.e. used only in the internal mappings and not exposed to users.

**Comment by bolshakov-a** [comment]
> Btw, fwd-decl uses of symbols from `__gnu_cxx` need not to be recategorized to full uses. They should simply not occur (except the case when a user writes it explicitly).

But I'm in doubt now. The standard [prohibits](https://timsong-cpp.github.io/cppwp/n4950/lex.name#3.1) declaring identifiers starting with a double underscore in user's code. But if you write:
```cpp
namespace __gnu_cxx {
  class SomeClass;
}
```
you define `__gnu_cxx` namespace, strictly speaking. And the standard doesn't allow it, IIUC. So, if a user writes `__gnu_cxx::SomeClass` in his code explicitly, he should not forward-declare but include the corresponding library header instead?

**Comment by bolshakov-a** [comment]
In fact, the fix of the original issue is simple:
```diff
--- a/iwyu_include_picker.cc
+++ b/iwyu_include_picker.cc
@@ -339,6 +339,8 @@ const IncludeMapEntry stdlib_cxx_symbol_map[] = {
   { "std::size_t", kPrivate, "<ctime>", kPublic },
   { "std::size_t", kPrivate, "<cuchar>", kPublic },
   { "std::size_t", kPrivate, "<cwchar>", kPublic },
+
+  { "std::array", kPrivate, "<array>", kPublic },
 };
```
However, I still want to make the full mapping of standard library symbols, which would correctly take into account forward-declarations from `<iosfwd>`.

**Comment by kimgr** [comment]
Fixed on master as of 309f9be69030b708bc4193755ddd4985d0947b22.
